export default {
  // title/nav bar & bottom nav bar
  primary: '#0c6980',
  //primary: '#4056a1',
  //primary: '#3399ff',
  // primary: '#f7287b',
  secondary: 'red',
  //secondary: '#c5cbe3',
  //secondary: '#80bfff',
  // secondary: '#c8a2c8',
  accent: '#c4dbe0',
  //accent: '#efe2ba',
  //accent: '#c717fc',
  // accent: '#c8a2c8',
  accent2: 'aliceblue',
  //accent2: '#c5cbe3',
  cancelButtonColor: '#00a8a8',
  //cancelButtonColor: '#f13c20',
  saveButtonColor: '#0c6980',
  //saveButtonColor: '#d79922',
  //defaultButtonColor: '#0055aa',
  defaultButtonColor: '#319eb9',
  //defaultButtonColor: '#d79922', // tany/browny colour
  radioButtonColor: 'black',
  error: '#f13c20',
  //saveButtonColor: 'yellow',
  buttonText: 'white',
  placeholderText: "#999999",
  dropdownText: 'black',
  inputBorderColor: '#858585',
  addCircle: 'black',
  modalColor: '#00a8a8',
  modalDropdownColor: '#1acece',
  headerText: '#c4dbe0',
  hamburgerMenu: '#c4dbe0'  
};