/* eslint-disable */
import { USER_CENTER } from './typeUserCenter'; //用户中心接口事件

export const NONE_ACTION = 'NONE_ACTION'; // 发布空事件，不进行任何处理
export const TOKEN_INIT_LOADING = 'TOKEN_INIT_LOADING'; // 开始加载token
export const TOKEN_INIT_DONE = 'TOKEN_INIT_DONE'; // token初始化完成
export const TOKEN_UPDATE_DONE = 'TOKEN_UPDATE_DONE'; // token更新完成
export const TOKEN_DELETE_DONE = 'TOKEN_DELETE_DONE'; // token删除完成
export const TOKEN_INIT_ERROR = 'TOKEN_INIT_ERROR'; // token初始化失败
export const TOKEN_FRESH_ERROR = 'TOKEN_FRESH_ERROR'; // token 刷新失败 重新发送一次请求新token的流程

export const HOTWORDS_GET_LOADING = 'HOTWORDS_GET_LOADING'; // 开始获取热词
export const HOTWORDS_GET_DONE = 'HOTWORDS_GET_DONE'; // 获取热词成功
export const HOTWORDS_GET_ERROR = 'HOTWORDS_GET_ERROR'; // 获取热词失败

export const VERSION_GET_LOADING = 'VERSION_GET_LOADING';
export const VERSION_GET_DONE = 'VERSION_GET_DONE';
export const VERSION_GET_ERROR = 'VERSION_GET_ERROR';

// 登录界面
export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN'; // 打开登录窗口
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE'; // 关闭登录窗口

//获取验证码
export const VCODE_GET_LOADING = 'VCODE_GET_LOADING';
export const VCODE_GET_DONE = 'VCODE_GET_DONE';
export const VCODE_GET_ERROR = 'VCODE_GET_ERROR';

//关闭验证码窗口
export const MODAL_CLOSE = 'MODAL_CLOSE';

//设置验证码类型
export const VOCDE_TYPE = 'VCODE_TYPE';

//错误提示
export const ALERT_ERR = 'ALERT_ERR';
export const CLEAR_ERR = 'CLEAR_ERR';

//登陆
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
// 设置密码成功
export const SETPWD_DONE = 'SETPWD_DONE';

export const CONFIGS_GET_LOADING = 'CONFIGS_GET_LOADING';
export const CONFIGS_GET_DONE = 'CONFIGS_GET_DONE';
export const CONFIGS_GET_ERROR = 'CONFIGS_GET_ERROR';

export const CONFIG_INDUSTRY_KPI_LOADING = 'CONFIG_INDUSTRY_KPI_LOADING';
export const CONFIG_INDUSTRY_KPI_DONE = 'CONFIG_INDUSTRY_KPI_DONE';
export const CONFIG_INDUSTRY_KPI_ERROR = 'CONFIG_INDUSTRY_KPI_ERROR';

// 搜索
export const SEARCH_SUGGEST_LOADING = 'SEARCH_SUGGEST_LOADING';
export const SEARCH_SUGGEST_DONE = 'SEARCH_SUGGEST_DONE';
export const SEARCH_SUGGEST_ERROR = 'SEARCH_SUGGEST_ERROR';
export const SEARCH_KEY_CHANGE = 'SEARCH_KEY_CHANGE';
export const SEARCH_HISTORY_GET = 'SEARCH_HISTORY_GET';
export const SEARCH_NEXT_PAGE = 'SEARCH_NEXT_PAGE'; // 加载下一页
export const SEARCH_TYPE_CHANGE = 'SEARCH_TYPE_CHANGE';

// 搜索过滤条件
export const SEARCH_FILTER_SORT_LOADING = 'SEARCH_FILTER_SORT_LOADING';
export const SEARCH_FILTER_SORT_DONE = 'SEARCH_FILTER_SORT_DONE';
export const SEARCH_FILTER_SORT_ERROR = 'SEARCH_FILTER_SORT_ERROR';

export const SEARCH_FILTER_REGION_LOADING = 'SEARCH_FILTER_REGION_LOADING';
export const SEARCH_FILTER_REGION_DONE = 'SEARCH_FILTER_REGION_DONE';
export const SEARCH_FILTER_REGION_ERROR = 'SEARCH_FILTER_REGION_ERROR';

export const SEARCH_FILTER_REGION_OPEN = 'SEARCH_FILTER_REGION_OPEN';
export const SEARCH_FILTER_SORT_OPEN = 'SEARCH_FILTER_SORT_OPEN';

export const SEARCH_FILTER_ACTIONS = 'SEARCH_FILTER_ACTIONS'; // 通用过滤事件

// 通用的调用api事件
const COMMON_API = {
    LOADING: 'API_SERVICE_LOADING', // 加载开始
    DONE: 'API_SERVICE_DONE',   // 加载完成
    ERROR: 'API_SERVICE_ERROR',  // 加载错误
    CLEAR: 'API_SERVICE_CLEAR',  // 清除数据
};

// 公司相关事件
const COMPANY = {
  YUQING: {
      LOADING: 'COMPANY_YUQING_LOADING', // 加载开始
      DONE: 'COMPANY_YUQING_DONE',   // 加载完成
      ERROR: 'COMPANY_YUQING_ERROR',  // 加载错误
      CLEAR: 'COMPANY_YUQING_CLEAR',  // 加载错误
  },
};

// 事件类型
export const EVENT_TYPE = {
    USER_CENTER,
    COMMON_API,
    COMPANY
};


//企业详情
export const COMPANY_DETAIL_BASE_LOADING = 'COMPANY_DETAIL_BASE_LOADING';
export const COMPANY_DETAIL_BASE_DONE = 'COMPANY_DETAIL_BASE_DONE';
export const COMPANY_DETAIL_BASE_ERROR = 'COMPANY_DETAIL_BASE_ERROR';

export const COMPANY_DETAIL_ATTENTION_LOADING = 'COMPANY_DETAIL_ATTENTION_LOADING';
export const COMPANY_DETAIL_ATTENTION_DONE = 'COMPANY_DETAIL_ATTENTION_DONE';
export const COMPANY_DETAIL_ATTENTION_ERROR = 'COMPANY_DETAIL_ATTENTION_ERROR';

// 上市公司
export const LISTEDCONPANY_INFO_LOADING = 'LISTEDCONPANY_INFO_LOADING';
export const LISTEDCONPANY_INFO_ERROR = 'LISTEDCONPANY_INFO_ERROR';
export const LISTEDCONPANY_INFO_DONE = 'LISTEDCONPANY_INFO_DONE';
export const LISTEDCONPANY_STOCKHOLDERT_DONE = 'LISTEDCONPANY_STOCKHOLDERT_DONE';
export const LISTEDCONPANY_STOCKHOLDERT_LOADING = 'LISTEDCONPANY_STOCKHOLDERT_LOADING';
export const LISTEDCONPANY_STOCKHOLDERT_ERROR = 'LISTEDCONPANY_STOCKHOLDERT_ERROR';
export const LISTEDCONPANY_NOTICE_DONE = 'LISTEDCONPANY_NOTICE_DONE';
export const LISTEDCONPANY_NOTICE_LOADING = 'LISTEDCONPANY_NOTICE_LOADING';
export const LISTEDCONPANY_NOTICE_ERROR = 'LISTEDCONPANY_NOTICE_ERROR';
export const LISTEDCOMPANY_FINACIALREPORT_DONE = 'LISTEDCOMPANY_FINACIALREPORT_DONE';
export const LISTEDCOMPANY_FINACIALREPORT_LOADING = 'LISTEDCOMPANY_FINACIALREPORT_LOADING';
export const LISTEDCOMPANY_FINACIALREPORT_ERROR = 'LISTEDCOMPANY_FINACIALREPORT_ERROR';
export const LISTEDCOMPANY_KPISHEET_LOADING = 'LISTEDCOMPANY_KPISHEET_LOADING';
export const LISTEDCOMPANY_KPISHEET_DONE = 'LISTEDCOMPANY_KPISHEET_DONE';
export const LISTEDCOMPANY_KPISHEET_ERROR = 'LISTEDCOMPANY_KPISHEET_ERROR';
export const LISTEDCOMPANY_BALANCESHEET_LOADING = 'LISTEDCOMPANY_BALANCESHEET_LOADING';
export const LISTEDCOMPANY_BALANCESHEET_DONE = 'LISTEDCOMPANY_BALANCESHEET_DONE';
export const LISTEDCOMPANY_BALANCESHEET_ERROR = 'LISTEDCOMPANY_BALANCESHEET_ERROR';
export const LISTEDCOMPANY_INCOMESHEET_LOADING = 'LISTEDCOMPANY_INCOMESHEET_LOADING';
export const LISTEDCOMPANY_INCOMESHEET_DONE = 'LISTEDCOMPANY_INCOMESHEET_DONE';
export const LISTEDCOMPANY_INCOMESHEET_ERROR = 'LISTEDCOMPANY_INCOMESHEET_ERROR';
export const LISTEDCOMPANY_CASHFLOW_LOADING = 'LISTEDCOMPANY_CASHFLOW_LOADING';
export const LISTEDCOMPANY_CASHFLOW_DONE = 'LISTEDCOMPANY_CASHFLOW_DONE';
export const LISTEDCOMPANY_CASHFLOW_ERROR = 'LISTEDCOMPANY_CASHFLOW_ERROR';
export const LISTEDCOMPANY_FINANCIALDATA_TYPE = 'LISTEDCOMPANY_FINANCIALDATA_TYPE';
// 上市公司行业分析加载
export const LISTEDCOMPANY_INDUSTRYANLYSIS_LOADING = 'LISTEDCOMPANY_INDUSTRYANLYSIS_LOADING';
export const LISTEDCOMPANY_INDUSTRYANLYSIS_DONE = 'LISTEDCOMPANY_INDUSTRYANLYSIS_DONE';
export const LISTEDCOMPANY_INDUSTRYANLYSIS_ERROR = 'LISTEDCOMPANY_INDUSTRYANLYSIS_ERROR';
export const LISTEDCOMPANY_INDUSTRYANLYSIS_CHANGE_ZHIBIAO = 'LISTEDCOMPANY_INDUSTRYANLYSIS_CHANGE_ZHIBIAO';

// 雪球实时更新
export const STOCK_PRICE_XUEQIU_LOADING = 'STOCK_PRICE_XUEQIU_LOADING';
export const STOCK_PRICE_XUEQIU_DONE = 'STOCK_PRICE_XUEQIU_DONE';
export const STOCK_PRICE_XUEQIU_ERROR = 'STOCK_PRICE_XUEQIU_ERROR';

// 通用列表信息加载
export const COMPANY_COMMON_SUBMODULE_LOADING = 'COMPANY_COMMON_SUBMODULE_LOADING';
export const COMPANY_COMMON_SUBMODULE_DONE = 'COMPANY_COMMON_SUBMODULE_DONE';
export const COMPANY_COMMON_SUBMODULE_ERROR = 'COMPANY_COMMON_SUBMODULE_ERROR';
export const COMPNAY_COMMON_SUBMODULE_RESET = 'COMPNAY_COMMON_SUBMODULE_RESET';

//工商信息
export const COMPANY_DETAIL_SHUIWUXINXI_LOADING = 'COMPANY_DETAIL_SHUIWUXINXI_LOADING';
export const COMPANY_DETAIL_SHUIWUXINXI_DONE = 'COMPANY_DETAIL_SHUIWUXINXI_DONE';
export const COMPANY_DETAIL_SHUIWUXINXI_ERROR = 'COMPANY_DETAIL_SHUIWUXINXI_ERROR';

//税务信息
export const COMPANY_DETAIL_HUANBAOXINXI_LOADING = 'COMPANY_DETAIL_HUANBAOXINXI_LOADING';
export const COMPANY_DETAIL_HUANBAOXINXI_DONE = 'COMPANY_DETAIL_HUANBAOXINXI_DONE';
export const COMPANY_DETAIL_HUANBAOXINXI_ERROR = 'COMPANY_DETAIL_HUANBAOXINXI_ERROR';

export const STOCK_PRICE_XUEQIU_RESET = 'STOCK_PRICE_XUEQIU_RESET';

// 资产估值
// 初始化数据
export const ASSET_VALUATION_INIT = 'ASSET_VALUATION_INIT';
export const ASSET_VALUATION_CHANGED_TAB = 'ASSET_VALUATION_CHANGED_TAB'; // 切换资产估值页面的一级菜单
export const ASSET_VALUATION_CHANGED_SUB_TAB = 'ASSET_VALUATION_CHANGED_SUB_TAB'; // 切换资产估值页面二级Tab菜单
export const ASSET_VALUATION_CHANGED_ESTATE_TAB = 'ASSET_VALUATION_CHANGED_ESTATE_TAB'; // 切换资产估值页面地产子菜单

export const ASSET_VALUATION_REGION_LOADING = 'ASSET_VALUATION_REGION_LOADING'; // 开始获取资产估值的地区列表
export const ASSET_VALUATION_REGION_DONE = 'ASSET_VALUATION_REGION_DONE'; // 获取资产估值的地区列表成功
export const ASSET_VALUATION_REGION_ERROR = 'ASSET_VALUATION_REGION_ERROR'; // 获取资产估值的地区列表失败

export const ASSET_VALUATION_CHANGED_HOUSE_ESTATE_STATE = 'ASSET_VALUATION_CHANGED_HOUSE_ESTATE_STATE'; // 资产估值页面选择小区

export const ASSET_VALUATION_RESIDENTIAL_QUARTER_LOADING = 'ASSET_VALUATION_RESIDENTIAL_QUARTER_LOADING'; // 开始获取资产估值的地区列表
export const ASSET_VALUATION_RESIDENTIAL_QUARTER_DONE = 'ASSET_VALUATION_RESIDENTIAL_QUARTER_DONE'; // 获取资产估值的地区列表成功
export const ASSET_VALUATION_RESIDENTIAL_QUARTER_ERROR = 'ASSET_VALUATION_RESIDENTIAL_QUARTER_ERROR'; // 获取资产估值的地区列表失败

// 初始化资产估值-房地产-小区搜索历史列表
export const ASSET_VALUATION_HOUSING_ESTATE_SEARCH_HISTORY_INIT = 'ASSET_VALUATION_HOUSING_ESTATE_SEARCH_HISTORY_INIT';

// 初始化资产估值-股票-搜索历史列表
export const ASSET_VALUATION_STOCK_SEARCH_HISTORY_INIT = 'ASSET_VALUATION_STOCK_SEARCH_HISTORY_INIT';

// 初始化资产估值-月份列表
export const ASSET_VALUATION_MONTH_LIST_LOADING = 'ASSET_VALUATION_MONTH_LIST_LOADING';
export const ASSET_VALUATION_MONTH_LIST_DONE = 'ASSET_VALUATION_MONTH_LIST_DONE';
export const ASSET_VALUATION_MONTH_LIST_ERROR = 'ASSET_VALUATION_MONTH_LIST_ERROR';

// 初始化资产估值-房产价格-单月
export const ASSET_VALUATION_HOUSE_MONTH_PRICE_LOADING = 'ASSET_VALUATION_HOUSE_MONTH_PRICE_LOADING';
export const ASSET_VALUATION_HOUSE_MONTH_PRICE_DONE = 'ASSET_VALUATION_HOUSE_MONTH_PRICE_DONE';
export const ASSET_VALUATION_HOUSE_MONTH_PRICE_ERROR = 'ASSET_VALUATION_HOUSE_MONTH_PRICE_ERROR';

// 初始化资产估值-房产价格-趋势
export const ASSET_VALUATION_HOUSE_TREND_LOADING = 'ASSET_VALUATION_HOUSE_TREND_LOADING';
export const ASSET_VALUATION_HOUSE_TREND_DONE = 'ASSET_VALUATION_HOUSE_TREND_DONE';
export const ASSET_VALUATION_HOUSE_TREND_ERROR = 'ASSET_VALUATION_HOUSE_TREND_ERROR';

// 资产估值-股票
export const ASSET_VALUATION_CHANGED_STOCK_STATE = 'ASSET_VALUATION_CHANGED_STOCK_STATE';

// 资产估值-股票-名称和代码查询
export const ASSET_VALUATION_STOCK_QUARTER_LOADING = 'ASSET_VALUATION_STOCK_QUARTER_LOADING';
export const ASSET_VALUATION_STOCK_QUARTER_DONE = 'ASSET_VALUATION_STOCK_QUARTER_DONE';
export const ASSET_VALUATION_STOCK_QUARTER_ERROR = 'ASSET_VALUATION_STOCK_QUARTER_ERROR';

// 资产估值-股票-估值查询
export const ASSET_VALUATION_STOCK_VALUE_LOADING = 'ASSET_VALUATION_STOCK_VALUE_LOADING';
export const ASSET_VALUATION_STOCK_VALUE_DONE = 'ASSET_VALUATION_STOCK_VALUE_DONE';
export const ASSET_VALUATION_STOCK_VALUE_ERROR = 'ASSET_VALUATION_STOCK_VALUE_ERROR';

// 资产估值-基金
export const ASSET_VALUATION_CHANGED_FUND_STATE = 'ASSET_VALUATION_CHANGED_FUND_STATE';

// 初始化资产估值-基金-搜索历史列表
export const ASSET_VALUATION_FUND_SEARCH_HISTORY_INIT = 'ASSET_VALUATION_FUND_SEARCH_HISTORY_INIT';

// 资产估值-基金-名称和代码查询
export const ASSET_VALUATION_FUND_QUARTER_LOADING = 'ASSET_VALUATION_FUND_QUARTER_LOADING';
export const ASSET_VALUATION_FUND_QUARTER_DONE = 'ASSET_VALUATION_FUND_QUARTER_DONE';
export const ASSET_VALUATION_FUND_QUARTER_ERROR = 'ASSET_VALUATION_FUND_QUARTER_ERROR';

// 资产估值-基金-单价查询
export const ASSET_VALUATION_FUND_PRICE_LOADING = 'ASSET_VALUATION_FUND_PRICE_LOADING';
export const ASSET_VALUATION_FUND_PRICE_DONE = 'ASSET_VALUATION_FUND_PRICE_DONE';
export const ASSET_VALUATION_FUND_PRICE_ERROR = 'ASSET_VALUATION_FUND_PRICE_ERROR';

// 资产估值-基金-单位净值趋势
export const ASSET_VALUATION_FUND_CHART_LOADING = 'ASSET_VALUATION_FUND_CHART_LOADING';
export const ASSET_VALUATION_FUND_CHART_DONE = 'ASSET_VALUATION_FUND_CHART_DONE';
export const ASSET_VALUATION_FUND_CHART_ERROR = 'ASSET_VALUATION_FUND_CHART_ERROR';

// 资产估值-基金-累计净值趋势
export const ASSET_VALUATION_FUND_CHART_TOTALS_LOADING = 'ASSET_VALUATION_FUND_CHART_TOTALS_LOADING';
export const ASSET_VALUATION_FUND_CHART_TOTALS_DONE = 'ASSET_VALUATION_FUND_CHART_TOTALS_DONE';
export const ASSET_VALUATION_FUND_CHART_TOTALS_ERROR = 'ASSET_VALUATION_FUND_CHART_TOTALS_ERROR';

// 资产估值-债券-输入状态变化
export const ASSET_VALUATION_CHANGED_BOND_STATE = 'ASSET_VALUATION_CHANGED_BOND_STATE';

// 初始化资产估值-债券-搜索历史列表
export const ASSET_VALUATION_BOND_SEARCH_HISTORY_INIT = 'ASSET_VALUATION_BOND_SEARCH_HISTORY_INIT';

// 资产估值-债券-名称和代码查询
export const ASSET_VALUATION_BOND_QUARTER_LOADING = 'ASSET_VALUATION_BOND_QUARTER_LOADING';
export const ASSET_VALUATION_BOND_QUARTER_DONE = 'ASSET_VALUATION_BOND_QUARTER_DONE';
export const ASSET_VALUATION_BOND_QUARTER_ERROR = 'ASSET_VALUATION_BOND_QUARTER_ERROR';

// 资产估值-债券-单价查询
export const ASSET_VALUATION_BOND_PRICE_LOADING = 'ASSET_VALUATION_BOND_PRICE_LOADING';
export const ASSET_VALUATION_BOND_PRICE_DONE = 'ASSET_VALUATION_BOND_PRICE_DONE';
export const ASSET_VALUATION_BOND_PRICE_ERROR = 'ASSET_VALUATION_BOND_PRICE_ERROR';

// 资产估值-债券-趋势
export const ASSET_VALUATION_BOND_CHART_LOADING = 'ASSET_VALUATION_BOND_CHART_LOADING';
export const ASSET_VALUATION_BOND_CHART_DONE = 'ASSET_VALUATION_BOND_CHART_DONE';
export const ASSET_VALUATION_BOND_CHART_ERROR = 'ASSET_VALUATION_BOND_CHART_ERROR';

// 资产估值-黄金-输入状态变化
export const ASSET_VALUATION_CHANGED_GOLD_STATE = 'ASSET_VALUATION_CHANGED_GOLD_STATE';

// 资产估值-黄金-种类查询
export const ASSET_VALUATION_GOLD_LIST_LOADING = 'ASSET_VALUATION_GOLD_LIST_LOADING';
export const ASSET_VALUATION_GOLD_LIST_DONE = 'ASSET_VALUATION_GOLD_LIST_DONE';
export const ASSET_VALUATION_GOLD_LIST_ERROR = 'ASSET_VALUATION_GOLD_LIST_ERROR';

// 资产估值-黄金-单价查询
export const ASSET_VALUATION_GOLD_PRICE_LOADING = 'ASSET_VALUATION_GOLD_PRICE_LOADING';
export const ASSET_VALUATION_GOLD_PRICE_DONE = 'ASSET_VALUATION_GOLD_PRICE_DONE';
export const ASSET_VALUATION_GOLD_PRICE_ERROR = 'ASSET_VALUATION_GOLD_PRICE_ERROR';

// 资产估值-黄金-价格趋势
export const ASSET_VALUATION_GOLD_CHART_LOADING = 'ASSET_VALUATION_GOLD_CHART_LOADING';
export const ASSET_VALUATION_GOLD_CHART_DONE = 'ASSET_VALUATION_GOLD_CHART_DONE';
export const ASSET_VALUATION_GOLD_CHART_ERROR = 'ASSET_VALUATION_GOLD_CHART_ERROR';

// 工商信息
export const BUSINESS_INFO_LOADING = 'BUSINESS_INFO_LOADING';
export const BUSINESS_INFO_DONE = 'BUSINESS_INFO_DONE';
export const BUSINESS_INFO_ERROR = 'BUSINESS_INFO_ERROR';

export const BUSINESS_EMPLOYEES_LOADING = 'BUSINESS_EMPLOYEES_LOADING';
export const BUSINESS_EMPLOYEES_DONE = 'BUSINESS_EMPLOYEES_DONE';
export const BUSINESS_EMPLOYEES_ERROR = 'BUSINESS_EMPLOYEES_ERROR';
// 法院判决详情信息
export const COMPANY_COURT_JUDGEINFO_LOADING = 'COMPANY_COURT_JUDGEINFO_LOADING';
export const COMPANY_COURT_JUDGEINFO_DONE = 'COMPANY_COURT_JUDGEINFO_DONE';
export const COMPANY_COURT_JUDGEINFO_ERROR = 'COMPANY_COURT_JUDGEINFO_ERROR';

// 失信信息详情信息
export const COMPANY_DISHONESTY_INFO_LOADING = 'COMPANY_DISHONESTY_INFO_LOADING';
export const COMPANY_DISHONESTY_INFO_DONE = 'COMPANY_DISHONESTY_INFO_DONE';
export const COMPANY_DISHONESTY_INFO_ERROR = 'COMPANY_DISHONESTY_INFO_ERROR';

// 资质认证
export const COMPANY_PERMISSION_LOADING = 'COMPANY_PERMISSION_LOADING';
export const COMPANY_PERMISSION_DONE = 'COMPANY_PERMISSION_DONE';
export const COMPANY_PERMISSION_ERROR = 'COMPANY_PERMISSION_ERROR';

// 股权关系 股权结构
export const COMPANY_EQUITY_STRUCT_LOADING = 'COMPANY_EQUITY_STRUCT_LOADING';
export const COMPANY_EQUITY_STRUCT_DONE = 'COMPANY_EQUITY_STRUCT_DONE';
export const COMPANY_EQUITY_STRUCT_ERROR = 'COMPANY_EQUITY_STRUCT_ERROR';

// 资金关系 投资关系
export const COMPANY_FUNDS_RELATION_LOADING = 'COMPANY_FUNDS_RELATION_LOADING';
export const COMPANY_FUNDS_RELATION_DONE = 'COMPANY_FUNDS_RELATION_DONE';
export const COMPANY_FUNDS_RELATION_ERROR = 'COMPANY_FUNDS_RELATION_ERROR';
export const COMPANY_FUNDS_RELATION_COMMON_ACTIONS = 'COMPANY_FUNDS_RELATION_COMMON_ACTIONS';

// 企业图谱相关types
export const COMPANY_CHAIN_MAP_LOADING = 'COMPANY_CHAIN_MAP_LOADING';
export const COMPANY_CHAIN_MAP_DONE = 'COMPANY_CHAIN_MAP_DONE';
export const COMPANY_CHAIN_MAP_ERROR = 'COMPANY_CHAIN_MAP_ERROR';
export const COMPANY_CHAIN_MAP_ACTIONS = 'COMPANY_CHAIN_MAP_ACTIONS';
export const COMPANY_CHAIN_MAP_SUB_LOADING = 'COMPANY_CHAIN_MAP_SUB_LOADING';
export const COMPANY_CHAIN_MAP_SUB_DONE = 'COMPANY_CHAIN_MAP_SUB_DONE';
export const COMPANY_CHAIN_MAP_SUB_ERROR = 'COMPANY_CHAIN_MAP_SUB_ERROR';


// 经营分析相关模块

export const BUSINESS_SUMMARY_LOADING = 'BUSINESS_SUMMARY_LOADING';
export const BUSINESS_SUMMARY_DONE = 'BUSINESS_SUMMARY_DONE';
export const BUSINESS_SUMMARY_ERROR = 'BUSINESS_SUMMARY_ERROR';
export const BUSINESS_SUMMARY_ACTIONS = 'BUSINESS_SUMMARY_ACTIONS';

export const BUSINESS_TOP_TEN_LOADING = 'BUSINESS_TOP_TEN_LOADING';
export const BUSINESS_TOP_TEN_DONE = 'BUSINESS_TOP_TEN_DONE';
export const BUSINESS_TOP_TEN_ERROR = 'BUSINESS_TOP_TEN_ERROR';
export const BUSINESS_TOP_TEN_ACTIONS = 'BUSINESS_TOP_TEN_ACTIONS';

export const BUSINESS_MAIN_AREA_LOADING = 'BUSINESS_MAIN_AREA_LOADING';
export const BUSINESS_MAIN_AREA_DONE = 'BUSINESS_MAIN_AREA_DONE';
export const BUSINESS_MAIN_AREA_ERROR = 'BUSINESS_MAIN_AREA_ERROR';
export const BUSINESS_MAIN_AREA_ACTIONS = 'BUSINESS_MAIN_AREA_ACTIONS';

export const BUSINESS_HOT_PRODUCT_LOADING = 'BUSINESS_HOT_PRODUCT_LOADING';
export const BUSINESS_HOT_PRODUCT_DONE = 'BUSINESS_HOT_PRODUCT_DONE';
export const BUSINESS_HOT_PRODUCT_ERROR = 'BUSINESS_HOT_PRODUCT_ERROR';
export const BUSINESS_HOT_PRODUCT_ACTIONS = 'BUSINESS_HOT_PRODUCT_ACTIONS';


// 热门企业
export const HOT_COMPANY_GET_LOADING = 'HOT_COMPANY_GET_LOADING';
export const HOT_COMPANY_GET_DONE = 'HOT_COMPANY_GET_DONE';
export const HOT_COMPANY_GET_ERROR = 'HOT_COMPANY_GET_ERROR';

// 热门应用
export const HOT_APPS_LOADING = 'HOT_APPS_LOADING';
export const HOT_APPS_DONE = 'HOT_APPS_DONE';
export const HOT_APPS_ERROR = 'HOT_APPS_ERROR';